name: Build Mac App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build app
      run: |
        pyinstaller --onefile --windowed ig_multi_profile_with_delete.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-app
        path: dist/ig_multi_profile_with_delete
